### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adolfoarmas**

### CODE REVIEW

**Review by marcbelmont — COMMENTED** [review]
I would rather remove everything and replace it with:

```
# Video Editor Utility

View the [documentation](https://guides.platerecognizer.com/docs/other/video-utils).
```

**Comment by adolfoarmas** [comment]
@marcbelmont done

**Review by marcbelmont — APPROVED** [review]

**Comment by marcbelmont** [comment]
ty, this way, if we add new features, we just need to update one documentation file.

**Comment by adolfoarmas** [comment]
Okay, it definitely makes sense.

**Pull request merged**
