### PR TITLE
Initial commit of people detection experiment

### PR DESCRIPTION
**Pull request by danleyb2**

### CODE REVIEW

**Comment by kal-tek** [comment]
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: Get "https://authn.nvidia.com/token?scope=repository%3Anvidia%2Fpytorch%3Apull%2Cpush&service=registry": dial tcp: lookup authn.nvidia.com: no such host`
This Error happend on docker build @danleyb2.  How should this be resolved?

**Comment by danleyb2** [comment]
@marcbelmont  changes: 
1. Stripping out code and features not needed to achieve the bare minimum of detecting **people** and **heads** in an image. 
2. Newly added code is in `main.py` and `webhook.py`

Loading `crowdhuman_yolov5m.pt` model without it's modification requires the folder structure of **models** and **utils** to be maintained. Otherwise you'd get module import errors.

@kal-tek Try pulling the base image directly `nvcr.io/nvidia/pytorch:20.12-py3` but you probably also need to [setup docker authentication to nvcr.io](https://forums.developer.nvidia.com/t/are-nvidia-docker-images-available-publicly/54619/4)

**Comment by marcbelmont** [comment]
@danleyb2 is there a smaller base image you could use?

**Comment by marcbelmont** [comment]
@kal-tek, is the readme enough, or should we add more details?

**Comment by kal-tek** [comment]
> @kal-tek, is the readme enough, or should we add more details?

Yes the readme is enough but not everyone has nvcr docker setup. the `man` page seems clear but i think it can elaborate more.

also the model `crowdhuman_yolov5m.pt` should be added on gitignore so that it wont be registered as new file.

**Comment by danleyb2** [comment]
@marcbelmont @kal-tek Have below changes so i think the branch is good:

- Added a way to build image with CPU only support. It's smaller than with GPU. I think choosing a different base might break GPU support but i can continue looking into it.
- Added .gitignore for model file
- Updated the README to be more useful and added new info

**Pull request merged**
