### PR TITLE
Create middleware_webhook_soap.py

### PR DESCRIPTION
**Pull request by adolfoarmas**

### CODE REVIEW

**Comment by AashishDhakal** [comment]
@adolfoarmas Can you please fix the indentation first? The Handler methods are not properly indented, hence won't work. `do_GET` and `do_POST` both should be inside the GetHandler class.

Also, make sure you run pre-commit after making the changes.

**Comment by AashishDhakal** [comment]
@adolfoarmas @marcbelmont did we try using `zeep` (https://docs.python-zeep.org) instead of `requests`. I think the code will be far more shorter and cleaner with `Zeep` for the SOAP services.

**Comment by adolfoarmas** [comment]
That could be great! 

I though so, but had to use request because the server has internet access disable but PR license check, so i couldn't run pip.

Besides that i can try asking for internet access and build it with zeep. LMK

**Comment by AashishDhakal** [comment]
Let's use Zeep if its possible. The data structures as well are more manageable that way, we can simply pass a dict instead of building the template.

**Comment by marcbelmont** [comment]
@adolfoarmas any updates?

**Comment by marcbelmont** [comment]
@adolfoarmas what is missing here?

**Comment by adolfoarmas** [comment]
@marcbelmont Not able to apply changes in server due to client is now testing current script version

**Comment by marcbelmont** [comment]
@adolfoarmas ok, let us know how it goes.

**Comment by adolfoarmas** [comment]
> Let's use Zeep if its possible. The data structures as well are more manageable that way, we can simply pass a dict instead of building the template.

updated with zeep library

**Pull request merged**
