### PR TITLE
Serve usb camera for windows

### PR DESCRIPTION
**Pull request by adolfoarmas**

### CODE REVIEW

**Comment by marcbelmont** [comment]
@adolfoarmas This technique looks inefficient as you are saving each frame as a jpeg. 
You could achieve a similar result more efficiently with https://github.com/bluenviron/mediamtx. 
@danleyb2, what are your thoughts?

**Comment by danleyb2** [comment]
@adolfoarmas Haven't done any performance comparison but I agree with @marcbelmont .
Installing FFMPEG and MediaMTX should be easier than Python and the script
Here is a procedure for Windows https://github.com/bluenviron/mediamtx?tab=readme-ov-file#by-device

**Comment by adolfoarmas** [comment]
@marcbelmont @danleyb2 hi, thanks for the feedback i didn't know MediaMTX. 
I'm going to give it a try, it should be more efficient.

**Comment by adolfoarmas** [comment]
@marcbelmont i did, it works well, i think it is better to place the tutorial directly on guides and discard this branch, what do you think?

**Comment by marcbelmont** [comment]
@adolfoarmas 
Ok, let's do that.

**Pull request closed without merging**
