### PR TITLE
update webhooks

### PR DESCRIPTION
**Pull request by ttayson**
File: webhook_reader_flask.py

- I made a small modification to the file to make it easier for the client to start the script with just a basic command without the need to export environment variables. 
- Fixed the handling of the file when no image is sent through the webhook. 

File: webhook_reader.py

- Fixed saving the upload with the pattern sent by the request. 
- Fixed the handling of the file when no image is sent through the webhook. 

File: webhook_reader.js
- Fixed the filename field in the request.
- Fixed the handling of the file when no image is sent through the webhook.

### CODE REVIEW

**Review by marcbelmont — COMMENTED** [review]
Did you test with https://github.com/parkpow/deep-license-plate-recognition/blob/master/webhooks/README.md#sending-data-to-the-webhook-server ?

**Comment by ttayson** [comment]
Test in : python3 webhook_reader.py
image

**Comment by ttayson** [comment]
Test in:  python3 webhook_reader_flask.py
image

**Comment by ttayson** [comment]
Test in : node webhook_reader.js
image

**Comment by ttayson** [comment]
@marcbelmont above are the tests made with the three edited scripts, webhook_tester always sends with the presence of an image with the name image.jpg

**Review by marcbelmont — APPROVED** [review]

**Pull request merged**
